default: &default
  adapter: postgresql
  encoding: unicode
  host: 127.0.0.1
  username: root
  password: p@ssw0rd
  pool: 5

development:
  <<: *default
  database: user_management_development

test:
  <<: *default
  database: user_management_test

production:
  <<: *default
  database: user_management_production
  username: user_management
  password: <%= ENV["USER_MANAGEMENT_DATABASE_PASSWORD"] %>
